# Generated by Django 5.2 on 2025-04-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nama_lengkap",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="jabatan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
